
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import static java.lang.System.console;
import java.nio.charset.StandardCharsets;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jbuda
 */
public class gui extends javax.swing.JFrame {

    String SourceLoc = "";
    String OutputLoc = "";
    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfcSourceFile = new javax.swing.JFileChooser();
        jfcOutput = new javax.swing.JFileChooser();
        txtSourceLoc = new javax.swing.JTextField();
        btnSourceLoc = new javax.swing.JButton();
        txtOutputLoc = new javax.swing.JTextField();
        btnOutputLoc = new javax.swing.JButton();
        jrbBec = new javax.swing.JRadioButton();
        jrbPak = new javax.swing.JRadioButton();
        jrbTok = new javax.swing.JRadioButton();
        jrbZlib = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btnExtract = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSourceLoc.setText("Source file lcoation here");
        txtSourceLoc.setEnabled(false);

        btnSourceLoc.setText("Find file to be extracted");
        btnSourceLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSourceLocActionPerformed(evt);
            }
        });

        txtOutputLoc.setText("Output folder here");
        txtOutputLoc.setEnabled(false);
        txtOutputLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOutputLocActionPerformed(evt);
            }
        });

        btnOutputLoc.setText("Choose output folder");
        btnOutputLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutputLocActionPerformed(evt);
            }
        });

        jrbBec.setSelected(true);
        jrbBec.setText("bec-tool");

        jrbPak.setText("pak-tool");
        jrbPak.setEnabled(false);

        jrbTok.setText("tok-tool");
        jrbTok.setEnabled(false);

        jrbZlib.setText("zlib-tool");
        jrbZlib.setEnabled(false);

        jLabel1.setText("Select a tool below:");

        btnExtract.setText("Extract files");
        btnExtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtractActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSourceLoc)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExtract, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrbTok)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbZlib))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrbBec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbPak))
                            .addComponent(jLabel1))
                        .addGap(0, 170, Short.MAX_VALUE))
                    .addComponent(btnSourceLoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtOutputLoc)
                    .addComponent(btnOutputLoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSourceLoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSourceLoc)
                .addGap(18, 18, 18)
                .addComponent(txtOutputLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOutputLoc)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbBec)
                    .addComponent(jrbPak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbTok)
                    .addComponent(jrbZlib))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExtract, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOutputLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOutputLocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOutputLocActionPerformed

   
    private void btnSourceLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSourceLocActionPerformed
        int returnVal = jfcSourceFile.showOpenDialog(this);
        File file = jfcSourceFile.getSelectedFile();
          // What to do with the file, e.g. display it in a TextArea
        txtSourceLoc.setText(file.getAbsolutePath());
        SourceLoc = file.getAbsolutePath();
    }//GEN-LAST:event_btnSourceLocActionPerformed

    private void btnOutputLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutputLocActionPerformed
        jfcOutput.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = jfcOutput.showOpenDialog(this);
        File directory = jfcOutput.getSelectedFile();
        txtOutputLoc.setText(directory.getAbsolutePath());
        OutputLoc = directory.getAbsolutePath();
    }//GEN-LAST:event_btnOutputLocActionPerformed

    private void btnExtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtractActionPerformed
        runBec(SourceLoc, OutputLoc);
    }//GEN-LAST:event_btnExtractActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }
    
    public void runBec(String SourceLoc, String OutputLoc){
        /* Neither of these work?????
        System.out.println("Starting runBec");
        String location = gui.class.getProtectionDomain().getCodeSource().getLocation().getPath();
        location = location.replaceAll("/", "\\\\");
        Process process = null;
        try{
            //process = Runtime.getRuntime().exec(new String[]{"cmd.exe python "+location + "bec-tool.py","-unpack", SourceLoc, OutputLoc, OutputLoc+ "\\gladius_bec_FileList.txt"});
            process = Runtime.getRuntime().exec(new String[]{"cmd.exe", "/c" ,"python", location + "bec-tool.py -unpack "+SourceLoc +" "+ OutputLoc + " " + OutputLoc + "\\gladius_bec_FileList.txt"});
       }catch(Exception e) {
          System.out.println("Exception Raised" + e.toString());
       }
       System.out.println("command loaded?");
       InputStream stdout = process.getInputStream();
       BufferedReader reader = new BufferedReader(new InputStreamReader(stdout,StandardCharsets.UTF_8));
       String line;
       try{
          while((line = reader.readLine()) != null){
               System.out.println("stdout: "+ line);
          }
       }catch(IOException e){
             System.out.println("Exception in reading output"+ e.toString());
       }*/
        //simpler way?
        try{
       String location = gui.class.getProtectionDomain().getCodeSource().getLocation().getPath();
       String[] cmdArray = new String[6];
       cmdArray[0] = "python";
       cmdArray[1] = location + "bec-tool.py";
       cmdArray[2] = "-unpack";
       cmdArray[3] = SourceLoc;
       cmdArray[4] = OutputLoc;
       cmdArray[5] = "gladius_bec_FileList.txt";
       Process process = Runtime.getRuntime().exec(cmdArray);
        } catch (Exception ex){
            ex.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExtract;
    private javax.swing.JButton btnOutputLoc;
    private javax.swing.JButton btnSourceLoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFileChooser jfcOutput;
    private javax.swing.JFileChooser jfcSourceFile;
    private javax.swing.JRadioButton jrbBec;
    private javax.swing.JRadioButton jrbPak;
    private javax.swing.JRadioButton jrbTok;
    private javax.swing.JRadioButton jrbZlib;
    private javax.swing.JTextField txtOutputLoc;
    private javax.swing.JTextField txtSourceLoc;
    // End of variables declaration//GEN-END:variables
}
